/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 02-sept-2026 11:40:29 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `articulo` CASCADE
;

/* Create Tables */

CREATE TABLE `articulo`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`descripcion` VARCHAR(200) NULL,
	`cantidad` INT NOT NULL,
	`estado` BOOL NOT NULL,
	CONSTRAINT `PK_Marticulo` PRIMARY KEY (`id` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1 
;
