/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-ago-2026 12:09:26 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `articulo` CASCADE
;

/* Create Tables */

CREATE TABLE `articulo`
(
	`idArticulo` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`descripcion` VARCHAR(200) NULL,
	`cantidad` INT NULL,
	`estado` BOOL NOT NULL,
	CONSTRAINT `PK_Marticulo` PRIMARY KEY (`idArticulo` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1 
;
